### ISSUE TITLE
Private Keys Error

### ISSUE THREAD

**Issue by caetanix** [kornrunner/php-ethereum-address#2]
I'm doing a checksum after the creation, and sometimes privatekeys only have 63 chars...

address: 2c10383ae14f59415979d7c232ca2c85b62c18a9
private: 93262d84237f92dc8e4409062dcc9dfc8cdc211ec32b18aa073af15841cd844

address: f81153ba99e401149c6d028eb39fd657e474e7c0
private: 7a51d7d4445c567c12639ca38e4c9fc4b12f6ec9f0aab82f98c28acaae446a3

thanks

**Comment by kornrunner** [comment]
`str_pad` should ensure we're getting 64 chars: https://github.com/kornrunner/php-ethereum-address/blob/master/src/Address.php#L31 - but it should have padded on the left, not on the right.

New version is released, thank you for reporting.
