### ISSUE TITLE
Call to undefined method Mdanter\Ecc\PrivateKey::getSecret()

### ISSUE THREAD

**Issue by WGAGlobal** [kornrunner/php-ethereum-address#6]
Hi all!

I have a problem on PHP 8.1.13:
Fatal error: Uncaught Error: Call to undefined method Mdanter\Ecc\PrivateKey::getSecret() in /path/vendor/kornrunner/ethereum-address/src/Address.php:31

Someone faced such a problem? What are some ideas for a solution?

**Comment by kornrunner** [comment]
How did you require/install this package? Are you using composer?

Mentioned class is provided by [mdanter/ecc](https://packagist.org/packages/mdanter/ecc) and is required by this package (see https://github.com/kornrunner/php-ethereum-address/blob/main/composer.json#L8)

**Comment by WGAGlobal** [comment]
Sorry, I had package for other PHP version. When I rebuilt packages all is work.

Thank you very much for your package!
